### ISSUE TITLE
admin dashboard: Shift Events "occurred at" column should show time of day

### ISSUE THREAD

**Issue by bjmllr** [rubyforgood/habitat_humanity#114]
When viewing the Shift Events dashboard, (i.e., `/admin/shift_events`), the "occurred at" column should show both date and time for each record, but only the date is shown. The full date and time can be seen by clicking through to events for a specific shift_events record.

**Comment by kctrlv** [comment]
This appears to be an issue with the administrate gem. 

An issue for this bug was opened [here](https://github.com/thoughtbot/administrate/issues/562) fairly recently, but it is still unresolved.

**Comment by kctrlv** [comment]
After digging in deeper and learning that Administrate lets you customize the views, I went ahead and added a custom view at app/views/admin/shift_events/_collection.html.erb in which there is a check to see if the attribute is a DateTime, in which case it renders it as a datetime instead of the way Administrate does it now (as a Date).
