### ISSUE TITLE
Signature report is hard to read on smalls screens

### ISSUE THREAD

**Issue by leesharma** [rubyforgood/habitat_humanity#66]
The signature report doesn't do well on mobile. Here's a screenshot from my laptop; note the field overflow:
![signature report on small screens](https://cloud.githubusercontent.com/assets/814638/16710058/3a1047f0-45f0-11e6-8552-378cf3d5ad0c.png)

We should probably have a mobile-optimized view if we expect this to be used on mobile devices.

**Comment by bjmllr** [comment]
We probably don't need the full report, though we might want a subset, so that a site supervisor can confirm that everyone has signed in.

@glazomaniac WDYT?

**Comment by glazomaniac** [comment]
The full report goes to Avery, the site supervisor gets a shorter one on her/his phone?

**Comment by leesharma** [comment]
If the site supervisor is the one who will be looking at this on their phone, should we be able to restrict the report by site as well?

**Comment by bjmllr** [comment]
That would be good. Because the app is global, someone might accidentally sign in to the wrong site, but other than troubleshooting that scenario, I guess a site supervisor would only want to know about the site they are supervising on the current day. Could look something like:

| volunteer_name | action |
| --- | --- |
| Ben | start_break |
| Sally | start_shift |
| Rob | end_shift |

**Comment by leesharma** [comment]
@bjmllr Second question: If multiple site supervisors are allowed to access this, does this mean we should allow for more than one admin? Or are supervisors a different role that still need to be added?

**Comment by bjmllr** [comment]
It's a separate User role ( #39 ) . Robb got us started on adding roles during R4G but we ended up de-prioritizing it.
